### PR TITLE
Fix permalink resolving when ref contains slashes

### LINKED ISSUE #61: Strange code rendering
Just seen this in the wild:

Nothing urgent, just thought it would be nice to report :)

Screenshot 2022-11-24 at 17 34 25

### PR DESCRIPTION
**Pull request by julien-nc**
closes #61

This is costly but I found no smarter way...

What's done now is to take the ref+path and loop to try to get the commit info from the longest candidate to the shortest. For example, with https://github.com/nextcloud/richdocuments/blob/testing/direct_edit/lib/Controller/WopiController.php#L22 , those requests will be made to `api.github.com/repos/nextcloud/richdocuments/commits/REF`:
* `testing/direct_edit/lib/Controller`
* `testing/direct_edit/lib`
* `testing/direct_edit` which is successful

### CODE REVIEW

**Comment by julien-nc** [comment]
Not sure I understand.
Do you mean set a timeout for the whole "search commit" loop?
Or set the timeout of each client request?
Or something else? :grin:

File: src/views/GithubCodePermalinkReferenceWidget.vue [hunk 1]
```diff
@@ -134,7 +134,10 @@ export default {
 				: t('integration_github', 'Line {line}', { line: this.richObject.lineBegin })
 		},
 		shortRef() {
-			return this.richObject.ref.slice(0, 7)
+			if (this.richObject.ref.original_ref === this.richObject.ref.sha) {
```
Comment (juliushaertl) [inline src/views/GithubCodePermalinkReferenceWidget.vue:137]: Is the sha already trimmed to 8 chars elsewhere?

Comment (julien-nc) [reply src/views/GithubCodePermalinkReferenceWidget.vue:137]: I don't know why I removed that. Anyway, the sha can always be shortened.

**Review by juliushaertl — APPROVED** [review]
